sequences = {'pnas': {'arna+arna': {'guide': 'CAAUGGAGUA',
                                    'target': 'UACUCCAUUG'},
                      'bdna+bdna': {'guide': 'CAATGGAGTA',
                                    'target': 'TACTCCATTG'}},
             'pnas_amber': {'arna+arna': {'guide': 'CAAUGGAGUA',
                                          'target': 'UACUCCAUUG'},
                            'bdna+bdna': {'guide': 'CAATGGAGTA',
                                          'target': 'TACTCCATTG'}},
             'pnas_clean': {'arna+arna': {'guide': 'CAAUGGAGUA',
                                          'target': 'UACUCCAUUG'},
                            'bdna+bdna': {'guide': 'CAATGGAGTA',
                                          'target': 'TACTCCATTG'}},
             'pnas_amber_clean': {'arna+arna': {'guide': 'CAAUGGAGUA',
                                                'target': 'UACUCCAUUG'},
                                  'bdna+bdna': {'guide': 'CAATGGAGTA',
                                                'target': 'TACTCCATTG'}},
             'pnas_16mer': {'arna+arna': {'guide': 'GCGCAAUGGAGUACGC', 'target': 'GCGUACUCCAUUGCGC'},
                                   'bdna+bdna': {'guide': 'GCGCAATGGAGTACGC', 'target': 'GCGTACTCCATTGCGC'}},
             'yizao_model': {'arna+arna': {'guide': 'CGCGAAUACUCGGAGCAAUUCGCG', 
                                           'target': 'CGCGAAUUGCUCCGAGUAUUCGCG'},
                             'bdna+bdna': {'guide': 'CGCGAATACTCGGAGCAATTCGCG', 
                                           'target': 'CGCGAATTGCTCCGAGTATTCGCG'}},
             'yizao_model_extension': {'arna+arna': {'guide': 'CGCGAAUACUCGGAGCAAUUCGCG', 
                                           'target': 'CGCGAAUUGCUCCGAGUAUUCGCG'},
                             'bdna+bdna': {'guide': 'CGCGAATACTCGGAGCAATTCGCG', 
                                           'target': 'CGCGAATTGCTCCGAGTATTCGCG'}},
             'yizao_model_1': {'arna+arna': {'guide': 'UUCAGUCUUUAUCUGUCUCUU', 
                                             'target': None},
                               'bdna+bdna': {'guide': 'TTCAGTCTTTATCTGTCTCTT', 
                                             'target': 'GAGACAGATAAAGACTGAAAA'}},
             'ttago': {'arna+arna': {'guide': '',
                                     'target': ''},
                       'bdna+bdna': {'guide': 'TGAGGTAGTAGGTTGTATAGT',
                                     'target': 'TATACAACCTACTACCTCGT'}},
             'only_cation': {'arna+arna': {'guide': 'GCGCAAUGGAGUACGC', 'target': 'GCGUACUCCAUUGCGC'},
                             'bdna+bdna': {'guide': 'GCGCAATGGAGTACGC', 'target': 'GCGTACTCCATTGCGC'}},
             '500mm': {'arna+arna': {'guide': 'GCGCAAUGGAGUACGC', 'target': 'GCGUACUCCAUUGCGC'},
                       'bdna+bdna': {'guide': 'GCGCAATGGAGTACGC', 'target': 'GCGTACTCCATTGCGC'}},
             'mgcl2_150mm': {'arna+arna': {'guide': 'GCGCAAUGGAGUACGC', 'target': 'GCGUACUCCAUUGCGC'},
                       'bdna+bdna': {'guide': 'GCGCAATGGAGTACGC', 'target': 'GCGTACTCCATTGCGC'}},
             'a_tract_21mer': {'bdna+bdna': {'guide': 'AAAAAAAAAAAAAAAAAAAAA', 'target': 'TTTTTTTTTTTTTTTTTTTTT'}},
             'g_tract_21mer': {'bdna+bdna': {'guide': 'GGGGGGGGGGGGGGGGGGGGG', 'target': 'CCCCCCCCCCCCCCCCCCCCC'}},
             'atat_21mer': {'bdna+bdna': {'guide': 'ATATATATATATATATATATA', 'target': 'TATATATATATATATATATAT'}},
             'gcgc_21mer': {'bdna+bdna': {'guide': 'GCGCGCGCGCGCGCGCGCGCG', 'target': 'CGCGCGCGCGCGCGCGCGCGC'}},
             'tgtg_21mer': {'bdna+bdna': {'guide': 'TGTGTGTGTGTGTGTGTGTGT', 'target': 'ACACACACACACACACACACA'}},
             'ctct_21mer': {'bdna+bdna': {'guide': 'CTCTCTCTCTCTCTCTCTCTC', 'target': 'GAGAGAGAGAGAGAGAGAGAG'}},
             'tat_21mer': {'bdna+bdna': {'guide': 'CGCAAAAAATATAAAAAAGCG', 'target': 'CGCTTTTTTATATTTTTTGCG'}}
             }
